# Generated by Django 3.0.3 on 2020-02-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200214_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='task',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
