# Generated by Django 3.0.3 on 2020-02-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_user_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
    ]
