# Generated by Django 3.0.3 on 2020-02-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20200214_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.DateField(blank=True, help_text='Day of the event', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Final time', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Textual Notes', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Starting time', null=True),
        ),
    ]
