# Generated by Django 3.0.3 on 2020-02-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20200215_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
