# Generated by Django 3.0.3 on 2020-02-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_auto_20200215_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
